### PR TITLE
Add GHA workflow

### PR DESCRIPTION
**Pull request by gbordyugov**
Add GHA workflow.

Please let me know if CI/CD is already running elsewhere.

### CODE REVIEW

**Review by dmigo — APPROVED** [review]
Отлично

**Comment by gbordyugov** [comment]
BTW, I cannot merge this PR nor the other one.

**Comment by hexeberlin** [comment]
> BTW, I cannot merge this PR nor the other one.

@afedulov could you please add @gbordyugov as collaborator to this repo?

**Comment by hexeberlin** [comment]
> Add GHA workflow.
> 
> Please let me know if CI/CD is already running elsewhere.

not yet! I would like to also automate this in future: https://github.com/afedulov/help-ukraine-bot/blob/master/README.md?plain=1#L19
e.g. automatically deploy changes to test version when opening a PR and then automatically deploy master once PR is mergen, but didn't have time to look into it 🙈

**Pull request merged**
